"""upd participation and add updating this model

Revision ID: 8b6805b5b565
Revises: ecd6977bde25
Create Date: 2025-04-03 14:16:43.369443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6805b5b565'
down_revision: Union[str, None] = 'ecd6977bde25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participations', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('participations', sa.Column('wb_nickname', sa.String(), nullable=True))
    op.add_column('participations', sa.Column('details_for_transfer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participations', 'details_for_transfer')
    op.drop_column('participations', 'wb_nickname')
    op.drop_column('participations', 'phone_number')
    # ### end Alembic commands ###
