"""add created at and ended at

Revision ID: 9f8aea265ebf
Revises: 1d4a1ee14740
Create Date: 2025-04-02 12:29:08.376270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8aea265ebf'
down_revision: Union[str, None] = '1d4a1ee14740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participations', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('participations', sa.Column('ended_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participations', 'ended_at')
    op.drop_column('participations', 'created_at')
    # ### end Alembic commands ###
